// Code generated by "stringer -type valueType -linecomment"; DO NOT EDIT.

package value

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[stringType-1]
	_ = x[intType-2]
	_ = x[floatType-3]
	_ = x[boolType-4]
	_ = x[arrayType-5]
	_ = x[objectType-6]
	_ = x[fileType-7]
	_ = x[formDataType-8]
	_ = x[requestType-9]
	_ = x[responseType-10]
	_ = x[cookieType-11]
	_ = x[streamType-12]
	_ = x[nameType-13]
	_ = x[zeroType-14]
}

const _valueType_name = "stringintfloatboolarrayobjectfileform-datarequestresponsecookiestreamnamezero"

var _valueType_index = [...]uint8{0, 6, 9, 14, 18, 23, 29, 33, 42, 49, 57, 63, 69, 73, 77}

func (i valueType) String() string {
	i -= 1
	if i >= valueType(len(_valueType_index)-1) {
		return "valueType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _valueType_name[_valueType_index[i]:_valueType_index[i+1]]
}
