// Code generated by "stringer -type valueType -linecomment"; DO NOT EDIT.

package value

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[stringType-1]
	_ = x[intType-2]
	_ = x[boolType-3]
	_ = x[arrayType-4]
	_ = x[objectType-5]
	_ = x[fileType-6]
	_ = x[requestType-7]
	_ = x[responseType-8]
	_ = x[streamType-9]
	_ = x[nameType-10]
	_ = x[zeroType-11]
}

const _valueType_name = "stringintboolarrayobjectfilerequestresponsestreamnamezero"

var _valueType_index = [...]uint8{0, 6, 9, 13, 18, 24, 28, 35, 43, 49, 53, 57}

func (i valueType) String() string {
	i -= 1
	if i >= valueType(len(_valueType_index)-1) {
		return "valueType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _valueType_name[_valueType_index[i]:_valueType_index[i+1]]
}
