// Code generated by "stringer -type LitType -linecomment"; DO NOT EDIT.

package syntax

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StringLit-1]
	_ = x[IntLit-2]
	_ = x[FloatLit-3]
	_ = x[BoolLit-4]
}

const _LitType_name = "stringintfloatbool"

var _LitType_index = [...]uint8{0, 6, 9, 14, 18}

func (i LitType) String() string {
	i -= 1
	if i >= LitType(len(_LitType_index)-1) {
		return "LitType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _LitType_name[_LitType_index[i]:_LitType_index[i+1]]
}
