// Code generated by "stringer -type Op -linecomment"; DO NOT EDIT.

package syntax

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EqOp-1]
	_ = x[NeqOp-2]
	_ = x[LtOp-3]
	_ = x[LeqOp-4]
	_ = x[GtOp-5]
	_ = x[GeqOp-6]
	_ = x[InOp-7]
	_ = x[AndOp-8]
	_ = x[OrOp-9]
}

const _Op_name = "==!=<<=>>=inandor"

var _Op_index = [...]uint8{0, 2, 4, 5, 7, 8, 10, 12, 15, 17}

func (i Op) String() string {
	i -= 1
	if i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
