// Code generated by "stringer -type Op -trimprefix O"; DO NOT EDIT.

package syntax

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OVAR-1]
	_ = x[OREF-2]
	_ = x[OREFDOT-3]
	_ = x[OREFIND-4]
	_ = x[OLIT-5]
	_ = x[ONAME-6]
	_ = x[OARR-7]
	_ = x[OOBJ-8]
	_ = x[OKEY-9]
	_ = x[OBLOCK-10]
	_ = x[OLIST-11]
	_ = x[OMETHOD-12]
	_ = x[OMATCH-13]
	_ = x[OCASE-14]
	_ = x[OYIELD-15]
	_ = x[OIF-16]
	_ = x[OOPEN-17]
	_ = x[OENV-18]
	_ = x[OEXIT-19]
	_ = x[OWRITE-20]
}

const _Op_name = "VARREFREFDOTREFINDLITNAMEARROBJKEYBLOCKLISTMETHODMATCHCASEYIELDIFOPENENVEXITWRITE"

var _Op_index = [...]uint8{0, 3, 6, 12, 18, 21, 25, 28, 31, 34, 39, 43, 49, 54, 58, 63, 65, 69, 72, 76, 81}

func (i Op) String() string {
	i -= 1
	if i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
